fix: ui fixes
Snowball-Finance/axial-frontend-old pull request #11
Opened 2021-11-02 17:56 UTC by ovasylenko

styling fixes

- cursor
- hidden  DEADLINE / GAS

2021-11-02 18:44 UTC, saito-sv requested changes

2021-11-02 18:44 UTC, saito-sv commented on src/components/advance-options/AdvancedOptions.tsx
> +        {ENABLE_GAS && (
we wont be needing deadline and gas, please remove it completely instead of hiding it. This should be the same for all components that  use deposit.

2021-11-03 00:32 UTC, ovasylenko commented on src/components/advance-options/AdvancedOptions.tsx
> +        {ENABLE_GAS && (
fixed

2021-11-04 19:17 UTC, saito-sv approved these changes
LGTM

2021-11-04 20:20 UTC, merged